pipelines:
  default:
    - step:
        caches:
          - node
        script: 
          - docker build -t ui .
          - docker run -p 3000:3000 -p 3001:3001 ui npm start && npm run e2e
        services:
          - docker
        